version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: langchain-postgres
    environment:
      POSTGRES_DB: langchain_chatbot
      POSTGRES_USER: langchain_user
      POSTGRES_PASSWORD: langchain_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langchain_user -d langchain_chatbot"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: langchain-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@langchain.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: 